@startuml
package Controller {

  class UserController {
    + registerUser(String affiliazione, String email, String lastname, String name, String password, String ruole): RUserDTO
    + login(email: String, password: String): RUserDTO
    + getRAuthorBYEmail (String Email): RUserDTO
  }

  class ConferenceController {
    + createConference(LocalDate scadenza, String title, String descr, ID id, RUserDTO org): void
    + getActiveConferences(): ArrayList<ShowActiveConferenceDTO>
    + getArticlesByConference(ID: ID_conference): ArrayList<ShowArticleDTO>
  }
  
  class ArticleController {
    + submitArticle(String article_titolotitolo, String article_abstrct,  ArrayList<RUserDTO> article_autori, ID id_conf): boolean
    + getArticleByAuthor(ID authorID): ArrayList<ShowArticleDTO>
  }

  class ReviewController {
    + assignReviewer(ID articleID, ArrayList<PossibleReviewDTO> list_r): boolean
    + getListReviewer(ID articleID): ArrayList<PossibleReviewDTO>
    + updateArticleStatus (ID id_article, String status): boolean
  }

  class NotificationController {
    + invioNotifiche(): void
    + creatMessage(String aut_name, String aut_lastname, String conf_title): String
    + sendEmail (String email_d, String conf_title, String msg): void
  }

}
@enduml
