@startuml
actor Autore as at
participant "Sistema" as ui
participant "Database" as db

activate at
activate ui
at -> ui: Inserimento dati articoli [Title, Abstract, Co-autori]
alt Conferenzza scelta  risulta esistente
alt Conferenzza scelta attiva
alt Autori presenti nel sistema
activate db
 ui -> db: L’articolo viene recipito e gli viene messo lo stato di ”sottomesso”
deactivate db
else Autori non presenti nel sistema
  ui -> at: Messaggio di errore
 end
else Conferenzza scelta non attiva
ui -> at: Messaggio di errore
end
else Conferenzza scelta non esistente
 ui -> at: Messaggio di errore
end

deactivate at
deactivate ui
@enduml
