@startuml
left to right direction
actor Utente
actor Autore
actor Organizzatore
actor Revisore

package Sistema {
	usecase Registrazione
	usecase Accesso
	usecase CreaConferenza
	usecase SottomettiArticolo
	usecase AssegnaRevisori
	usecase NotificaScadenza
	usecase InserimentoEsitoRevisione
	usecase VerificaConflittiInteresse
}

'Definizione ereditarietà tra ruoli
Utente <|- Autore
Utente <|- Organizzatore
Autore <|- Revisore
'Definizione interazione Usecase <-> Attori
Utente -- Registrazione
Utente -- Accesso
Autore -- SottomettiArticolo
Organizzatore -- CreaConferenza
Organizzatore -- AssegnaRevisori
AssegnaRevisori -r- Revisore
Revisore -- InserimentoEsitoRevisione
AssegnaRevisori ..|> VerificaConflittiInteresse: <<include>>
NotificaScadenza -- Autore

@enduml
