@startuml
actor Organizzatore as or
actor Autore as at
participant "Sistema" as ui
participant "Database" as db

activate or
activate ui
or->ui: inserimento dati conferenza [title,description,deadline]
ui->ui: Verifica dati inseriti
alt Tutti dati validi
activate db
activate at
    ui->db: Creazione della conferenza
    ui->at: Conferenza disponibile per tutti autori
deactivate at
else Data non valida
    ui->or: Messaggio di errore
else Data nel passato
    ui->or: Messaggio di errore
end
deactivate ui
deactivate or
deactivate db
@enduml
