@startuml

actor User as US
participant "Sistema" as UI
participant "GestionePermessiVisibilita" as PV

activate US
activate UI

US -> UI : Inserimento Credenziali: login(email, password)
UI->UI : Validazione Credenziali

alt Credenziali Valide
activate PV
UI -> PV : Credenziali valide
PV -> US : Redirezione alla pagina in base al ruolo dell'utente
else Email già Presente 
UI -> US : Accesso Negato: Messaggio di errore
else Credenziali Non Valide 
UI -> US : Accesso Negato: Messaggio di errore
else Email inserita non valida 
UI -> US : Accesso Negato: Messaggio di errore
end

deactivate US
deactivate UI
deactivate PV
@enduml