@startuml
actor Organizzatore as org
participant "Sistema" as ui
participant "VerificaConflittiInteresse" as vc
participant "InserimentoEsitoRevisione" as rev

activate org
activate ui
org -> ui: Selezione dell'articolo da revisionare
org -> ui: Selezione della data di fine revisione
org -> ui: Selezione dei revisori
activate vc
alt data di scadenza rispetata
ui -> vc: Verifica di conflitti
vc -> ui: Esito verifica conflitti
alt Verifica dei conflitti di interesse negativa
activate rev
    ui -> ui: Aggiornamento stato "sottomesso" -> "in revisione"
    rev -> ui: Inserimento esito della revisione dell'articolo
alt Inserimento esito revisione positivo
    ui -> ui: Aggiornamento stato da "in revisione"->"approvato"
else Inserimento esito revisione negativo
    ui -> ui: Aggiornamento stato da "in revisione"->"rifiutato"
end
else Verifica dei conflitti di interesse negativa
    ui -> org: Richiesta di riassegnazione dei revisori
end
else Data di scadenza non rispettata
    ui -> ui: Aggiornamento stato da "in revisione"->"rifiutato"
end
deactivate rev
deactivate vc
deactivate ui
deactivate org
@enduml
