@startuml
package DTO{

    class PossibleReviewDTO {
        - id: ID 
        - name: String
        - lastname: String
        - affiliazione: String
        + PossibleReviewDTO(id: ID, name: String, lastname: String, affiliazione: String),
        + PossibleReviewDTO(autore: Author),
        + getId(): ID
        + getName(): String
        + getLastname(): String
        + getAffiliation(): String
    }

    class RUserDTO {
        - name: String
        - lastname: String
        - email: String
        - affiliazione: String
        - ruolo: String
        - id: ID
        + RUserDTO(name: String, lastname: String, email: String, affiliazione: String, ruolo: String, id: ID),
        + RUserDTO(user User),
        + RUserDTO(Ruser RUserDTO),
        + getName(): String
        + getLastname(): String
        + getEmail(): String
        + getAffiliation(): String
        + getRole(): String
        + getId(): ID
    }

    class ShowActiveConferenceDTO {
        - id: ID 
        - titolo: String
        - scadenza: Date
        - descrizione: String
        + ShowActiveConferenceDTO(id: ID ,titolo: String ,scadenza: Date, decrizione: String),
        + ShowActiveConferenceDTO(active_conference: ShowActiveConferenceDTO),
        + ShowActiveConferenceDTO(conference: Conference),
        + getId(): ID
        + getTitle(): String
        + getDeadline(): Date
        + getDescription(): String
    }

    class ShowArticleDTO {
        - id: ID 
        - titolo: String
        - abstr: String
        - autori: ArrayList<RUserDTO>
        + ShowArticleDTO(id: ID,titolo: String, abstr: String, autori: ArrayList<RUserDTO>),
        + ShowArticleDTO(article: Article),
        + ShowArticleDTO(article_dto: ShowArticleDTO),
        + getId(): ID
        + getTitle(): String
        + getAbstr(): String
        + getAuthors(): ArrayList<RUserDTO>
    }

}
@enduml