@startuml 

class ConferenceManager {
  + submitArticle(author: Author, article: Article, conf: Conference)
  + assignReviewer(reviewer: Author, article: Article)
  + getSubmissions(conf: Conference): List<Article>
  + setArticleStatus(article: Article, status: String)
}

  abstract class User {
    - id: int
    - name: String
    - lastName: String
    - email: String
    - Affiliazione: String
    # User(aff: String, email: String, lastName: String, name: String, password: String, id: String);
    # User(u: User)
    + getName(): String
    + getLastName(): String
    + getEmail(): String
    + getId(): int
    + getAffiliazione(): String
    + setAffiliazione(aff: String): void
    + setEmail(email: String): void
  }
  
  class Author {
    - final role: String
    + Author(aff: String, email: String, lastName: String, name: String, password: String, id: String)
    + Author(a: Author)		
    + getRole(): String
  }

  class Organizer {
    - final role: String
    + Organizer(aff: String, email: String, lastName: String, name: String, password: String, id: String)
    + Organizer(o: Organizer)
    + getRole(): String
  }

  class Article {
    - title: String
    - abstract: String
    - status: String
    - coAuthors: List<Author>
    + Article(id: String, abstract: String, coAuthors: List<Author>, title: String)
    + Article(a: Article)
  }
  
  class Conference {
    - title: String
    - description: String
    - deadline: Date
    - articles: List<Article>
    + Conference(deadline: Date, title: String, description: String, id: String)
    + Conference(conf: Conference)
    + getTitle(): String
    + getDescription(): String
    + getDeadline(): Date
    + getArticles(): List<Article>
  }

  User <|-- Author
  User <|-- Organizer


Organizer "1" -- "1" ConferenceManager : Manages
ConferenceManager "1" -- "0..*" Conference : Knows about
ConferenceManager "1" -- "0..*" Article : Knows about
ConferenceManager "1" -- "0..*" Author : Knows about

' Relazioni
Organizer "1" -- "0..*" Conference : Gestisce
Conference "1" -- "0..*" Article : Sottomesso a
Article "1" -- "0..*" Author : Scritto da

' Revisori: relazione molti-a-molti tra Autore e Articolo
Author "0..*" -- "3" Article : <<revisore>>

@enduml
