@startuml
start

:[1] article_id = ID.generate();
:[2] authors_list = new ArrayList<>();

if ("Conference present?" [3]) then (no)
  :[4] "Conference not found";
  stop
else (yes)
  if ("Conference expired?" [6]) then (yes)
    :[7] "The selected conference is expired";
    stop
  else (no)
    if ("Authors list empty?" [9]) then (yes)
      :[10] "List of authors is empty";
      stop
    else (no)
      :for each fake_user in article_autori [12];
      if ("Valid author?" [13]) then (yes)
        :[14] add author to authors_list;
      else (no)
        -->[12] continue loop;
      endif
    endif
  endif
endif

if ("authors_list empty?" [15]) then (yes)
  :[16] "List of authors is empty";
  stop
else (no)
  :[18] create Article;
  :[19] add Article to conference;
  :[20] save Article;
  :[21] submit Article to conference;
  :[22] return true;
  stop
endif

@enduml
